### ISSUE TITLE
Vanilla swing desynchronised

### ISSUE THREAD

**Issue by TheKodeToad** [Polyfrost/OverflowAnimationsV2#1]
I'm guessing this mod internally never triggers the vanilla swing animation and instead simulates it. I'm pretty sure it's possible to update the vanilla animation without making servers upset - but it requires modifying private fields.

 
[Screencast from 2023-03-06 11-39-56.webm](https://user-images.githubusercontent.com/57493648/223100697-256294db-ea43-4b5f-83c4-25aec9611254.webm)

Steps to reproduce:
- Start using an item.
- Peform a single hit.
- Stop using the item.

**Comment by Wyvest** [comment]
can we have a screenshot of your settings

**Comment by TheKodeToad** [comment]
here you go!
![image](https://user-images.githubusercontent.com/57493648/223187938-08799242-1d98-40e3-9ea1-527b6975d67b.png)
GIMP image editor <3

**Comment by Mixces** [comment]
This issue should be resolved now

**Comment by TheKodeToad** [comment]
Totally missed that! Thank you!
