### ISSUE TITLE
Re-equip is spelt Re-quip in section title

### ISSUE THREAD

**Issue by ManInMyVan** [Polyfrost/OverflowAnimationsV2#12]
![typo](https://github.com/Polyfrost/OverflowAnimationsV2/assets/113963219/ae4090d2-1718-40db-9811-df8af444a89d)

**Comment by Mixces** [comment]
> ![typo](https://private-user-images.githubusercontent.com/113963219/342441571-ae4090d2-1718-40db-9811-df8af444a89d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNTM5MjIsIm5iZiI6MTcxOTI1MzYyMiwicGF0aCI6Ii8xMTM5NjMyMTkvMzQyNDQxNTcxLWFlNDA5MGQyLTE3MTgtNDBkYi05ODExLWRmOGFmNDQ0YTg5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxODI3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMWI4MDdlOWU0NzVmODBmMzE4ZmI5YWVhYzRmYjE3NTA0ZjY3NDc3NjI5NjdkNGRmN2VhNzM0YWMxZTdjZTliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XsAZf-13cvyRFrkwNeZe2dcTsFLa9hsrVKx40s2ZLJ4)

😭 😭 😭

**Comment by Mixces** [comment]
ill fix it 👍
