### ISSUE TITLE
disable re-equip does not affect switching to and from empty slots

### ISSUE THREAD

**Issue by ManInMyVan** [Polyfrost/OverflowAnimationsV2#13]
https://streamable.com/t4qxec

**Comment by Mixces** [comment]
good catch

**Comment by Mixces** [comment]
> https://streamable.com/t4qxec

I have fixed the issue in my latest commit! Please try it out and let me know if it's working :D

**Comment by ManInMyVan** [comment]
> I have fixed the issue in my latest commit! Please try it out and let me know if it's working :D

seems to work properly now
