### ISSUE TITLE
Disable swinging at the ground in adventure option is not working regardless of whether it is toggled on or off

### ISSUE THREAD

**Issue by AmirAbdi2017** [Polyfrost/OverflowAnimationsV2#17]
it doesn't let me swing on ground (v2.2.5), however it works on OverflowAnimations 2.1.1

**Comment by Mixces** [comment]
Hi, are you still experiencing this issue?

**Comment by AmirAbdi2017** [comment]
Hello, i reported this issue in the discord server, they said they'll look
into it
