### ISSUE TITLE
Rod rendered mirrored when 1.7 item transformations is disabled

### ISSUE THREAD

**Issue by 182exe** [Polyfrost/OverflowAnimationsV2#3]
![image](https://user-images.githubusercontent.com/81325987/225397792-f9c04e1d-1032-4049-8859-c03be34e55ca.png)
It's just mirrored.

**Comment by Wyvest** [comment]
> ![image](https://user-images.githubusercontent.com/81325987/225397792-f9c04e1d-1032-4049-8859-c03be34e55ca.png)
> It's just mirrored.

do you have "1.7 Item Transformations" off?

**Comment by 182exe** [comment]
yes

**Comment by Wyvest** [comment]
> yes
> but that probably shouldnt cause the rod to do that

it does because turning off the feature leaves it up to the resource pack to transform. keep it on
